name: Blackduck Scan PR
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
      - 'add-final-blackduck-version'

permissions:
  checks: write

jobs:
  blackduck:
    name: Black Duck SCA
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1_19_x
      - name: Run Black Duck SCA
        uses: synopsys-sig/detect-action@v0_3_4
        env:
          #DETECT_PROJECT_GROUP_NAME: opencomponentmodel
          DETECT_PROJECT_NAME: open-component-model/ocm
          DETECT_PROJECT_USER_GROUPS: opencomponentmodel
          DETECT_PROJECT_VERSION: main
          DETECT_SOURCE_PATH: _/
          #LOGGING_LEVEL_COM_SYNOPSYS_INTEGRATION: DEBUG
          DETECT_PROJECT_VERSION_DISTRIBUTION: SAAS
          DETECT_TIMEOUT: 6000
          DETECT_BLACKDUCK_SIGNATURE_SCANNER_MEMORY: 4096
          BLACKDUCK_TRUST_CERT: true
          NODE_TLS_REJECT_UNAUTHORIZED: true
        with:
          scan-mode: RAPID
          #scan-mode: INTELLIGENT
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 9.0.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}